version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: node node -e 'console.log("oi")'
  test:
    docker:
      - image: node
    steps:
      - checkout
      - run: node node -e 'console.log("oi")'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "*/1 * * * *"
          filters:
            branches:
              only:
                - master
                - dev
    jobs:
      - build
      - test